/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./*.html",
    "./blog/**/*.html",
    "./assets/app-screens/**/*.html",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#0A0A0A",
        "on-secondary-container": "#1b1c1c",
        "surface-container": "#eeeeec",
        "secondary-fixed": "#c7c6c6",
        "tertiary-fixed": "#5d5f5c",
        "on-background": "#1a1c1b",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#1b1c1c",
        "surface-variant": "#e2e3e1",
        "on-error": "#ffffff",
        "on-surface-variant": "#474747",
        "on-surface": "#1a1c1b",
        "outline-variant": "#E0E0DC",
        "tertiary-fixed-dim": "#464744",
        "surface-dim": "#dadad8",
        "surface-container-high": "#e8e8e6",
        "surface-bright": "#f9f9f7",
        "on-primary-fixed": "#ffffff",
        "on-primary-fixed-variant": "#e5e2e1",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f1f1ef",
        "on-primary-container": "#ffffff",
        "tertiary": "#3a3c39",
        "secondary-fixed-dim": "#ababab",
        "background": "#FFFFFF",
        "surface-container-highest": "#e2e3e1",
        "secondary": "#5e5e5e",
        "outline": "#888888",
        "on-tertiary": "#e3e3df",
        "on-tertiary-container": "#ffffff",
        "inverse-primary": "#c9c6c5",
        "error-container": "#ffdad6",
        "secondary-container": "#d5d4d4",
        "on-secondary": "#ffffff",
        "tertiary-container": "#747572",
        "inverse-surface": "#2f3130",
        "primary-fixed": "#5f5e5e",
        "on-error-container": "#410002",
        "on-secondary-fixed-variant": "#3b3b3c",
        "primary-fixed-dim": "#474646",
        "surface-container-low": "#F5F5F3",
        "surface": "#FFFFFF",
        "surface-tint": "#5f5e5e",
        "on-tertiary-fixed": "#ffffff",
        "primary-container": "#3c3b3b",
        "on-tertiary-fixed-variant": "#e3e3df"
      },
      fontFamily: {
        "serif": ["Playfair Display", "serif"],
        "sans": ["DM Sans", "sans-serif"],
        "headline": ["Playfair Display", "serif"],
        "display": ["Playfair Display", "serif"],
        "body": ["DM Sans", "sans-serif"],
        "label": ["DM Sans", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
