/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./*.html",
    "./blog/**/*.html",
    "./assets/app-screens/**/*.html",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#000000",
        "accent": "#1F5F4A",
        "accent-dim": "#174A3A",
        "accent-bright": "#3F9A78",
        "accent-container": "#E3EFE9",
        "on-accent": "#FFFFFF",
        "on-accent-container": "#0F3A2C",
        "on-primary": "#ffffff",
        "primary-container": "#1c1b1b",
        "on-primary-container": "#858383",
        "primary-fixed": "#e5e2e1",
        "primary-fixed-dim": "#c9c6c5",
        "on-primary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#474646",
        "inverse-primary": "#c9c6c5",
        "secondary": "#5e5e5e",
        "on-secondary": "#ffffff",
        "secondary-container": "#e3e2e2",
        "on-secondary-container": "#646464",
        "secondary-fixed": "#e3e2e2",
        "secondary-fixed-dim": "#c7c6c6",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary-fixed-variant": "#464747",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1a1c1a",
        "on-tertiary-container": "#838481",
        "tertiary-fixed": "#e3e3df",
        "tertiary-fixed-dim": "#c6c7c3",
        "on-tertiary-fixed": "#1a1c1a",
        "on-tertiary-fixed-variant": "#464744",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface": "#ffffff",
        "surface-dim": "#dddddd",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f7f7f7",
        "surface-container": "#f2f2f2",
        "surface-container-high": "#ececec",
        "surface-container-highest": "#e6e6e6",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#444748",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f4f0ef",
        "outline": "#747878",
        "outline-variant": "#c4c7c7",
        "surface-variant": "#e6e6e6",
        "surface-tint": "#5f5e5e",
        "background": "#ffffff",
        "on-background": "#1c1b1b",
      },
      borderRadius: {
        "none": "0",
        "sm": "2px",
        "DEFAULT": "4px",
        "md": "6px",
        "lg": "8px",
        "xl": "10px",
        "2xl": "12px",
        "3xl": "14px",
        "full": "9999px",
      },
      spacing: {
        "base": "4px",
        "xs": "8px",
        "sm": "16px",
        "md": "24px",
        "gutter": "24px",
        "lg": "40px",
        "xl": "64px",
        "container-max": "1200px",
      },
      fontFamily: {
        "body-md": ["Manrope"],
        "body-lg": ["Manrope"],
        "body-sm": ["Manrope"],
        "display-lg": ["Noto Serif"],
        "display-lg-mobile": ["Noto Serif"],
        "headline-md": ["Noto Serif"],
        "headline-sm": ["Noto Serif"],
        "label-caps": ["Manrope"],
        "numeric-lg": ["Noto Serif"],
        /* Fallback aliases for secondary pages */
        "serif": ["Noto Serif", "serif"],
        "sans": ["Manrope", "sans-serif"],
        "headline": ["Noto Serif", "serif"],
        "display": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "numeric-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
